Reposition search
ubuntudesign/developer.ubuntu.com pull request #254
Opened 2017-04-28 10:27 UTC by grahambancroft

## Done

Reposition search and make header taller

## QA

- Run ./run to get started
- Go to http://localhost:8015/core
- Make sure search is right aligned on large and that small works as expected
- The styling is as per live but I’m going to take a second pass at this to make it better

2017-04-28 11:00 UTC, anthonydillon requested changes
One suggestion in code

2017-04-28 11:00 UTC, anthonydillon commented on templates/includes/base/header.html
> +            <img src="{{ ASSET_SERVER_URL }}19750a6d-search-black.svg" class="header-search__image--small-screen" alt="Perform a search" />
Could you make this an optimised inline SVG and change the fill colour based on a media query? To save a request.

2017-04-28 11:11 UTC, anthonydillon commented
I know you said you were going for a second pass but I will mention that the placeholder colour should be white:
![welcome - developer](https://cloud.githubusercontent.com/assets/1413534/25526349/131960d0-2c0b-11e7-9358-bb63a68e2fc9.png)

On medium screens, the search hover area does not take up the entire height of the navigation:
![welcome - developer 1](https://cloud.githubusercontent.com/assets/1413534/25526480/98060f5a-2c0b-11e7-9121-5ac9998eb1bf.png)

Also, the small screen navigation does not work.

2017-04-28 11:12 UTC, anthonydillon commented
Thanks, @grahambancroft, looking good. Few comments above.

2017-04-28 12:50 UTC, grahambancroft commented on templates/includes/base/header.html
> +            <img src="{{ ASSET_SERVER_URL }}19750a6d-search-black.svg" class="header-search__image--small-screen" alt="Perform a search" />
These were already in place, I think they’re just white space changes, in the interest of MVP would it be okay for me to add the improvement as an issue?

2017-04-28 14:39 UTC, grahambancroft commented
Travis CI fix here https://github.com/vanilla-framework/vanilla-framework/pull/1050

2017-04-28 14:53 UTC, grahambancroft commented
Added placeholder and focus color to input

2017-04-28 15:12 UTC, grahambancroft commented
Fixed search hover, this was an issue on live also

2017-04-28 23:23 UTC, anthonydillon commented on templates/includes/base/header.html
> +            <img src="{{ ASSET_SERVER_URL }}19750a6d-search-black.svg" class="header-search__image--small-screen" alt="Perform a search" />
Sure

2017-04-28 23:28 UTC, anthonydillon commented on templates/includes/base/header.html
> +        <label for="edit-keys" class="header-search__label">Search</label>
For="search"?

2017-04-29 14:13 UTC, grahambancroft commented on templates/includes/base/header.html
> +        <label for="edit-keys" class="header-search__label">Search</label>
Fixed. Not entirely sure how this search stuff got through QA in the first place tbh

2017-04-30 18:43 UTC, anthonydillon commented
Looking good but one issue. On 820px the search box is toggled but the text is still white.
![core - developer](https://cloud.githubusercontent.com/assets/1413534/25567045/45f8ebc8-2ddd-11e7-88e6-206850223c67.png)

2017-05-01 18:28 UTC, grahambancroft commented
Fixed

2017-05-01 19:38 UTC, anthonydillon commented
I don't see a commit with the fix. Do you still have to push?

2017-05-02 08:01 UTC, anthonydillon approved these changes
Code and QA :+1:

2017-05-02 08:03 UTC, merged