Enable homepage as markdown file
ubuntudesign/developer.ubuntu.com pull request #263
Opened 2017-05-02 17:20 UTC by grahambancroft

## Done

Enable homepage as markdown file

## QA

- Run ./run to get started
- Go to http://0.0.0.0:8015/
- Make sure the copy is the same as the copy doc and that there are feeds from insights and tutorials

Doc: https://docs.google.com/document/d/1bvQDL9UlLMx8DFNQTCELPB4I3qBNwSV-OAig7z5-Jts/edit

2017-05-02 21:18 UTC, anthonydillon requested changes
Some questions in the code and QA was ok but missing content from "Target platforms" down.

2017-05-02 21:18 UTC, anthonydillon commented on templates/includes/components/homepage.html
> +                <div class="u-equal-height">
Otherwise, you can't use more then 12-col in a strip.

2017-05-02 21:18 UTC, anthonydillon commented on templates/pages/index.html
> +    <main id="main-content" class="p-layout__inner">
Is this file used?

2017-05-02 21:18 UTC, anthonydillon commented on templates/pages/index.md
> +# Millions of developers use Ubuntu to write, build and deploy their code
Is this file used?

2017-05-03 10:12 UTC, grahambancroft commented on templates/includes/components/homepage.html
> +        <div class="p-divider">
No, fixed

2017-05-03 10:12 UTC, grahambancroft commented on templates/includes/components/homepage.html
> +                <div class="u-equal-height">
Added

2017-05-03 10:12 UTC, grahambancroft commented on templates/pages/index.html
> +    <main id="main-content" class="p-layout__inner">
it’s not, I’ve removed

2017-05-03 10:12 UTC, grahambancroft commented on templates/pages/index.md
> +# Millions of developers use Ubuntu to write, build and deploy their code
it is yes

2017-05-03 13:33 UTC, anthonydillon approved these changes

2017-05-03 13:33 UTC, anthonydillon commented
@grahambancroft Thanks :+1:

2017-05-03 14:05 UTC, merged