My apps
ubuntudesign/developer.ubuntu.com pull request #268
Opened 2017-05-08 08:18 UTC by grahambancroft

## Done

Add ‘my apps’ link to main nav
Remove search specific breakpoint and use medium instead

## QA

- Run ./run to get started and go to http://0.0.0.0:8015/
- Check that the my apps link is on the right hand side but not visible on mobile
- Check that the search snaps at breakpoint-medium

2017-05-08 08:19 UTC, grahambancroft commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add ‘my apps’ link to main nav](https://trello.com/c/KBaXSt5p/3235-add-my-apps-link-to-main-nav)

2017-05-09 09:02 UTC, anthonydillon requested changes
Some questions in the code. QA ok but how do you get to My Apps on small screens?

2017-05-09 09:02 UTC, anthonydillon commented on templates/includes/base/header.html
> +            <li class="p-navigation__link"><a class="" href="https://myapps.developer.ubuntu.com/">My Apps</a></li>
Remove empty class on a tag.

2017-05-09 09:02 UTC, anthonydillon commented on templates/includes/base/header.html
> +            <li class="p-navigation__link"><a class="" href="https://myapps.developer.ubuntu.com/">My Apps</a></li>
Should this be external?

2017-05-09 10:08 UTC, grahambancroft commented on templates/includes/base/header.html
> +            <li class="p-navigation__link"><a class="" href="https://myapps.developer.ubuntu.com/">My Apps</a></li>
It should really, I’ve added the class and tweaked the SASS

2017-05-09 10:56 UTC, anthonydillon approved these changes
Code :+1:

2017-05-09 10:56 UTC, merged