Add canonical-global-nav as a dependency
ubuntudesign/developer.ubuntu.com pull request #270
Opened 2017-05-08 14:17 UTC by grahambancroft

## Done

Add canonical-global-nav as a dependency

## QA

- Run 'npm install -g bower'
- Run 'bower install canonical-global-nav'
- Run './run'
- Pop on over to http://0.0.0.0:8015 and make sure the global nav is visible
- Check in l, m and s

2017-05-08 23:40 UTC, anthonydillon requested changes
Looks like you have left in a npm install of the global nav. Can you remove this please.

2017-05-08 23:40 UTC, anthonydillon commented on package.json
> +    "global-nav": "0.0.2",
We should only be using the bower package. We don't need the npm one here.

2017-05-09 08:15 UTC, anthonydillon commented
@nottrobin also here. I thought `./run` supported bower? Does it just need to be updated?

2017-05-09 08:24 UTC, grahambancroft commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add global nav](https://trello.com/c/0eSelS4K/3236-add-global-nav)

2017-05-09 08:29 UTC, grahambancroft commented on package.json
> +    "global-nav": "0.0.2",
Removed

2017-05-09 08:30 UTC, grahambancroft commented
I’ll check with Will or Robin re the ./run question

2017-05-09 10:58 UTC, anthonydillon commented
The final think to make travis happy is to add:
https://github.com/canonical-websites/www.ubuntu.com/pull/1729/commits/00ddc12ce9b502454a8c788e0191f355511bf59c and https://github.com/canonical-websites/www.ubuntu.com/pull/1729/commits/436db453b738b2e9aa0cd84bec16f151568e7d7c

2017-05-09 13:54 UTC, anthonydillon commented
@grahambancroft looks like you have some lint issue here.

2017-05-09 14:19 UTC, anthonydillon commented
QA issue:
The margin on the global-nav on large screen size (>1000px) is missing margin so touching the edge of the screen.
![welcome - developer 2](https://cloud.githubusercontent.com/assets/1413534/25855362/e54316ce-34ca-11e7-9ea7-e945f634906e.png)

2017-05-09 15:13 UTC, grahambancroft commented
both issues fixed

2017-05-09 15:46 UTC, anthonydillon approved these changes

2017-05-09 15:47 UTC, anthonydillon commented
Nice one.

2017-05-09 15:47 UTC, merged