Main nav tweaks
ubuntudesign/developer.ubuntu.com pull request #280
Opened 2017-05-14 09:44 UTC by grahambancroft

## Done

Reinstate burger menu but for sidebar nav and only pages without children

## QA

- Run ./run and go to http://0.0.0.0:8015/ 
- Check the nav in s/m & l
- There should be no burger on /core pages and the nav should be open by default

2017-05-14 09:49 UTC, grahambancroft commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add burger menu for all but core section](https://trello.com/c/SDuHJLgY/3245-add-burger-menu-for-all-but-core-section)

2017-05-15 09:15 UTC, WillMoggridge requested changes
Two points raised, otherwise good

2017-05-15 09:15 UTC, WillMoggridge commented on templates/includes/components/sidebar_nav.html
> +<ul id="navigation" class="p-sidebar-nav__list u-clearfix {% if is_root %}js-mobile-no-collapse{% endif %}">
Did you mean to inverse the `if is_root` logic? I thought we just reverted it back to `if not`

2017-05-15 09:15 UTC, WillMoggridge commented on templates/includes/base/header.html
> +    {% if 'core' in request.path %}{% else %}
Can you create an issue to un-hardcode the core section here after this is merged, please. :)

2017-05-15 09:58 UTC, grahambancroft commented on templates/includes/components/sidebar_nav.html
> +<ul id="navigation" class="p-sidebar-nav__list u-clearfix {% if is_root %}js-mobile-no-collapse{% endif %}">
Reverted

2017-05-15 09:58 UTC, grahambancroft commented on templates/includes/base/header.html
> +    {% if 'core' in request.path %}{% else %}
sure thing

2017-05-15 12:30 UTC, grahambancroft commented
Hi @WillMoggridge this is ready for review again if you’d be so kind

2017-05-15 12:37 UTC, WillMoggridge approved these changes

2017-05-15 12:37 UTC, merged