Markdown extensions and table of contents
ubuntudesign/developer.ubuntu.com pull request #99
Opened 2016-12-07 16:15 UTC by WillMoggridge

- Markdown extensions
- Anchor links
- Table of contents on documentation pages

This change moves direct view markdown parsing, into the view itself. The main reason is that it means the view can access the table of contents and display it on the page anywhere the template decides.

The TOC is added to the documentation page_type, and we will need to add this page_type to pages shortly. It needs a little more styling but the functionality works!

2016-12-07 18:24 UTC, nottrobin requested changes
A few suggestions

2016-12-07 18:24 UTC, nottrobin commented on webapp/lib/markdown/markdown.py
> +def parse_markdown(markdown_content):
Flatten thjis function

2016-12-07 18:24 UTC, nottrobin commented on webapp/lib/markdown/markdown.py
> +        except TemplateDoesNotExist:
Maybe don't override the original exception?

2016-12-07 18:24 UTC, nottrobin commented on webapp/loaders.py
> +                except TemplateDoesNotExist:
Should we be passing over this error?

2016-12-08 10:23 UTC, WillMoggridge commented on webapp/loaders.py
> +                except TemplateDoesNotExist:
OK, I remember now after sleep!
We are looping over the loaders and requesting template names. It expects it to return this exception sometimes.

So, the first loader may return the exception, then the second one finds the template.

2016-12-08 10:24 UTC, nottrobin requested changes
Some formatting points

2016-12-08 10:24 UTC, nottrobin commented on webapp/views.py
Formatting: remove extra whitespace

2016-12-08 10:24 UTC, nottrobin commented on webapp/views.py
> +        for loader in loaders:
formatting: masks earlier `loader` declaration

2016-12-08 10:24 UTC, nottrobin commented on webapp/views.py
>  from webapp.lib.markdown import parse_frontmatter
formatting: imported but unused

2016-12-08 10:24 UTC, nottrobin commented on webapp/views.py
> +# from webapp.lib.markdown import get_markdown_with_parser
formatting: please remove commented out code

2016-12-08 10:53 UTC, WillMoggridge commented
Updated

2016-12-08 11:12 UTC, nottrobin approved these changes

2016-12-08 11:12 UTC, merged